# Maven


trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: SynopsysSecurityScan@1
  inputs:
    scanType: 'srm'
    srmUrl: 'https://srm.codexsecure.com/'
    srmApikey: 'api-key:r3N-m0YhKWkEsKa7ugESl8SEwr7pYdy9asl6_otC'
    srmAssessmentTypes: 'SAST'
    srmProjectName: 'Test'