# Maven


trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: SynopsysSecurityScan@1
  inputs:
    scanType: 'coverity'
    bridge_coverity_connect_url: 'https://coverity.codexsecure.com/'
    bridge_coverity_connect_user_name: 'admin'
    bridge_coverity_connect_user_password: 'C0verity@-Sys7781*'
    bridge_coverity_connect_project_name: 'Easy-Bugy'
    bridge_coverity_connect_stream_name: 'main'